export const products = {
  guitars: [
    {
      id: 100,
      product: "guitars",
      name: "Fender Telecaster",
      brand: "Fender",
      price: 1899.99,
      type: "Electric",
      color: "Blackguard Blonde",
      strings: "6",
      img: "00.webp",
      sold: 100,
      stars: "5",
      featured: false,
    },
    {
      id: 101,
      product: "guitars",
      name: "Fender Stratocaster",
      brand: "Fender",
      price: 1699.99,
      type: "Electric",
      color: "Sapphire Blue",
      strings: "6",
      img: "01.webp",
      sold: 5,
      stars: "4",
      featured: false,
    },
    {
      id: 102,
      product: "guitars",
      name: "Fender Jazzmaster",
      brand: "Fender",
      price: 1099.99,
      type: "Electric",
      color: "Surf Green",
      strings: "6",
      img: "02.webp",
      sold: 20,
      stars: "5",
      featured: false,
    },
    {
      id: 103,
      product: "guitars",
      name: "PRS CE 24",
      brand: "PRS",
      price: 1999.99,
      type: "Electric",
      color: "Amber",
      strings: "6",
      img: "03.webp",
      sold: 5,
      stars: "4",
      featured: false,
    },
    {
      id: 104,
      product: "guitars",
      name: "PRS Silver Sky",
      brand: "PRS",
      price: 2299.99,
      type: "Electric",
      color: "Frost",
      strings: "6",
      img: "04.webp",
      sold: 5,
      stars: "5",
      featured: true,
    },
    {
      id: 105,
      product: "guitars",
      name: "PRS Custom 24 'Floyd' 10-Top",
      brand: "PRS",
      price: 4299.99,
      type: "Electric",
      color: "Faded Whale Blue",
      strings: "6",
      img: "05.webp",
      sold: 5,
      stars: "5",
      featured: false,
    },
    {
      id: 106,
      product: "guitars",
      name: "PRS Custom 22 Piezo",
      brand: "PRS",
      price: 3999.99,
      type: "Electric",
      color: "Charcoal",
      strings: "6",
      img: "06.webp",
      sold: 5,
      stars: "5",
      featured: false,
    },
    {
      id: 107,
      product: "guitars",
      name: "ESP E-II Eclipse",
      brand: "ESP",
      price: 1999.99,
      type: "Electric",
      color: "Snow White",
      strings: "6",
      img: "07.webp",
      sold: 75,
      stars: "5",
      featured: false,
    },
    {
      id: 108,
      product: "guitars",
      name: "ESP LTD M-1000 HT",
      brand: "ESP",
      price: 1099.99,
      type: "Electric",
      color: "Black Fade",
      strings: "6",
      img: "08.webp",
      sold: 80,
      stars: "5",
      featured: false,
    },
    {
      id: 109,
      product: "guitars",
      name: "ESP LTD M-1007 Multi-Scale",
      brand: "ESP",
      price: 1299.99,
      type: "Electric",
      color: "Black Satin",
      strings: "7",
      img: "09.webp",
      sold: 5,
      stars: "5",
      featured: false,
    },
    {
      id: 110,
      product: "guitars",
      name: "Martin 00-15M",
      brand: "Martin",
      price: 1299.99,
      type: "Acoustic",
      color: "Natural Mahogany",
      strings: "6",
      img: "10.webp",
      sold: 11,
      stars: "5",
      featured: true,
    },
    {
      id: 111,
      product: "guitars",
      name: "Taylor GS Mini Rosewood",
      brand: "Taylor",
      price: 549.99,
      type: "Acoustic",
      color: "Natural",
      strings: "6",
      img: "11.webp",
      sold: 5,
      stars: "5",
      featured: false,
    },
  ],
  pedals: [
    {
      id: 200,
      product: "pedals",
      name: "Matthews Effects Chemist V2",
      brand: "Matthews Effects",
      price: 199.99,
      type: ["Chorus", "Vibrato", "Phaser"],
      signal: "Digital",
      img: "00.png",
      sold: 3,
      stars: "5",
      featured: true,
    },
    {
      id: 201,
      product: "pedals",
      name: "Walrus Audio Julia V2",
      brand: "Walrus Audio",
      price: 199.99,
      type: ["Chorus", "Vibrato"],
      signal: "Analog",
      img: "01.png",
      sold: 3,
      stars: "5",
      featured: true,
    },
    {
      id: 202,
      product: "pedals",
      name: "Pro Co Rat 2",
      brand: "Pro Co",
      price: 69.99,
      type: ["Distortion", "Overdrive"],
      signal: "Analog",
      img: "02.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 203,
      product: "pedals",
      name: "Strymon BigSky",
      brand: "Strymon",
      price: 479.99,
      type: ["Reverb"],
      signal: "Digital",
      img: "03.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 204,
      product: "pedals",
      name: "Fulltone OCD",
      brand: "Fulltone",
      price: 129.99,
      type: ["Distortion", "Overdrive"],
      signal: "Digital",
      img: "04.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 205,
      product: "pedals",
      name: "Walrus Audio Iron Horse",
      brand: "Walrus Audio",
      price: 199.99,
      type: ["Distortion"],
      signal: "Analog",
      img: "05.webp",
      sold: 65,
      stars: "5",
      featured: false,
    },
    {
      id: 206,
      product: "pedals",
      name: "TC ELectronic Hall of Fame 2",
      brand: "TC Electronic",
      price: 149.99,
      type: ["Reverb"],
      signal: "Digital",
      img: "06.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 207,
      product: "pedals",
      name: "TC Electronic Flashback 2",
      brand: "TC Electronic",
      price: 159.99,
      type: ["Delay", "Looper"],
      signal: "Digital",
      img: "07.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 208,
      product: "pedals",
      name: "Strymon TimeLine",
      brand: "Strymon",
      price: 449.99,
      type: ["Delay"],
      signal: "Digital",
      img: "08.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 209,
      product: "pedals",
      name: "TC Electronic Ditto X2",
      brand: "TC Electronic",
      price: 179.99,
      type: ["Looper"],
      signal: "Digital",
      img: "09.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 210,
      product: "pedals",
      name: "Keeley Aria",
      brand: "Keeley",
      price: 199.99,
      type: ["Compressor", "Overdrive"],
      signal: "Analog",
      img: "10.webp",
      sold: 3,
      stars: "5",
      featured: false,
    },
    {
      id: 211,
      product: "pedals",
      name: "MXR Mini Phase 95 ",
      brand: "MXR",
      price: 99.99,
      type: ["Phaser"],
      signal: "Analog",
      img: "11.png",
      sold: 3,
      stars: "5",
      featured: false,
    },
  ],
  accessories: [
    {
      id: 300,
      product: "accessories",
      name: "Mogami XLR Cable",
      brand: "Mogami",
      price: 39.99,
      type: "Cable",
      img: "00.webp",
      sold: 15,
      stars: "5",
      featured: false,
    },
    {
      id: 301,
      product: "accessories",
      name: 'Mogami Gold 1/4" Cable',
      brand: "Mogami",
      price: 49.99,
      type: "Cable",
      img: "01.webp",
      sold: 40,
      stars: "5",
      featured: false,
    },
    {
      id: 302,
      product: "accessories",
      name: 'Ernie Ball Braided 1/4" Cable',
      brand: "Ernie Ball",
      price: 29.99,
      type: "Cable",
      img: "02.webp",
      sold: 20,
      stars: "5",
      featured: false,
    },
    {
      id: 303,
      product: "accessories",
      name: "Fender Variety Medium Guitar Picks",
      brand: "Fender",
      price: 4.99,
      type: "Pick",
      img: "03.webp",
      sold: 50,
      stars: "5",
      featured: false,
    },
    {
      id: 304,
      product: "accessories",
      name: "Dunlop Tortex 0.5mm Guitar Picks",
      brand: "Dunlop",
      price: 4.99,
      type: "Pick",
      img: "04.webp",
      sold: 40,
      stars: "5",
      featured: false,
    },
    {
      id: 305,
      product: "accessories",
      name: "Dunlop Tortex 1mm Guitar Picks",
      brand: "Dunlop",
      price: 4.99,
      type: "Pick",
      img: "05.webp",
      sold: 40,
      stars: "5",
      featured: false,
    },
    {
      id: 306,
      product: "accessories",
      name: "Snark Clip-on Guitar Tuner",
      brand: "Snark",
      price: 12.99,
      type: "Tuner",
      img: "06.webp",
      sold: 35,
      stars: "5",
      featured: false,
    },
    {
      id: 307,
      product: "accessories",
      name: "Ernie Ball Polylock Guitar Strap",
      brand: "Ernie Ball",
      price: 34.99,
      type: "Strap",
      img: "07.webp",
      sold: 20,
      stars: "5",
      featured: false,
    },
    {
      id: 308,
      product: "accessories",
      name: "Fender Guitar Strap",
      brand: "Fender",
      price: 19.99,
      type: "Strap",
      img: "08.webp",
      sold: 15,
      stars: "5",
      featured: false,
    },
    {
      id: 309,
      product: "accessories",
      name: "Kyser Capo",
      brand: "Kyser",
      price: 16.99,
      type: "Capo",
      img: "09.webp",
      sold: 25,
      stars: "5",
      featured: false,
    },
    {
      id: 310,
      product: "accessories",
      name: "Shubb Capo",
      brand: "Shubb",
      price: 20.99,
      type: "Capo",
      img: "10.webp",
      sold: 35,
      stars: "5",
      featured: false,
    },
  ],
};
